#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Generates src/entities.js, the named character references HTML defines,
# from Python's html.entities.html5. Only the names that end in `;` are
# kept: tern passes a reference through only when it is terminated.
#   python3 tools/entities.py          (from any directory)
#
# Encoding (decoded by the generated file, once, on first use):
# - the 52-letter Fraktur, double-struck and script alphabets (`Afr`, `aopf`,
#   `Zscr`, ...) follow a rule; only the names the rule gets wrong are listed;
# - the other names are sorted and front-coded; each record is one prefix
#   character (how many characters it shares with the previous name), the
#   value, then the rest of the name, in which frequent substrings are
#   replaced by single punctuation characters;
# - a value's first code point in the densest 928-code-point range of
#   mathematical symbols is moved into U+0460...U+07FF, which HTML's values
#   leave free, so it takes two bytes of UTF-8 instead of three;
# - `fjlig` (the one value whose second character is ASCII) is added by hand.

import collections
import os
from html.entities import html5

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'entities.js')
NAMES = {k[:-1]: v for k, v in html5.items() if k.endswith(';')}
BASES = {'fr': 0x1D504, 'opf': 0x1D538, 'scr': 0x1D49C}
PUNCT = [chr(c) for c in range(33, 127) if not chr(c).isalnum() and chr(c) not in '\'\\']
WINDOW = (0x460, 0x800)  # free two-byte UTF-8 code points
MAXP = 11  # a longer shared prefix is rare; capping it frees characters for tokens
TOKENS = len(PUNCT) - MAXP - 1


def by_rule(name):
    for suffix, base in BASES.items():
        if len(name) == len(suffix) + 1 and name.endswith(suffix) and 'A' <= name[0].upper() <= 'Z':
            c = name[0]
            return chr(base + (ord(c) - 65 if c.isupper() else 26 + ord(c) - 97))
    return None


def main():
    table = {n: v for n, v in NAMES.items() if by_rule(n) != v and n != 'fjlig'}
    for n, v in table.items():
        assert len(v) in (1, 2), n
        assert not (WINDOW[0] <= ord(v[0]) < WINDOW[1]), n
        if len(v) == 2:
            assert 0x80 <= ord(v[1]) < 0x10000, n
    width = WINDOW[1] - WINDOW[0]
    count = collections.Counter(ord(v[0]) for v in table.values())
    shift = max((c for c in count if 0x800 <= c < 0x10000), key=lambda s: sum(n for c, n in count.items() if s <= c < s + width))

    names = sorted(table)
    max_prefix = 0
    records = []
    prev = ''
    for n in names:
        p = 0
        while p < min(len(n), len(prev), MAXP) and n[p] == prev[p]:
            p += 1
        max_prefix = max(max_prefix, p)
        records.append([p, table[n], n[p:]])
        prev = n
    prefix_chars = max_prefix + 1
    assert prefix_chars + TOKENS <= len(PUNCT)

    tokens = []
    for t in range(TOKENS):
        seen = collections.Counter()
        for r in records:
            s = r[2]
            for length in range(2, 9):
                for i in range(len(s) - length + 1):
                    sub = s[i:i + length]
                    if sub.isalnum():
                        seen[sub] += 1
        best = max(seen, key=lambda k: (seen[k] * (len(k) - 1), k))
        tokens.append(best)
        mark = PUNCT[prefix_chars + t]
        for r in records:
            r[2] = r[2].replace(best, mark)

    def value(v):
        c = ord(v[0])
        first = chr(c - shift + WINDOW[0]) if shift <= c < shift + width else v[0]
        return first + v[1:]

    data = ''.join(PUNCT[p] + value(v) + s for p, v, s in records)
    esc = {'\\': '\\\\', "'": "\\'", '\n': '\\n', '\t': '\\t', '\u2028': '\\u2028', '\u2029': '\\u2029'}
    literal = ''.join(esc.get(ch, ch) for ch in data)
    bases = ', '.join(f"{k}: 0x{v:X}" for k, v in BASES.items())
    src = f"""// SPDX-License-Identifier: MIT
// Generated by tools/entities.py from Python's html.entities.html5; do not
// edit. The {len(NAMES)} named character references HTML defines, compressed
// as the generator describes, and decode() for the body of a reference,
// between `&` and `;`.
'use strict';

const P = '{''.join(PUNCT)}';
const T = {tokens!r};
const BASES = {{ {bases} }};
const D =
  '{literal}';

let map = null;

function build() {{
  map = Object.create(null);
  const code = new Int8Array(128).fill(-1);
  for (let k = 0; k < P.length; k++) code[P.charCodeAt(k)] = k;
  let name = '';
  for (let i = 0; i < D.length; ) {{
    name = name.slice(0, code[D.charCodeAt(i++)]);
    let c = D.codePointAt(i);
    i += c > 0xffff ? 2 : 1;
    if (c >= 0x{WINDOW[0]:x} && c < 0x{WINDOW[1]:x}) c += 0x{shift - WINDOW[0]:x};
    let v = String.fromCodePoint(c);
    if (D.charCodeAt(i) >= 0x80) v += D[i++];
    for (let k; i < D.length && !((k = code[D.charCodeAt(i)]) >= 0 && k < {prefix_chars}); i++) name += k >= {prefix_chars} ? T[k - {prefix_chars}] : D[i];
    map[name] = v;
  }}
  map.fjlig = 'fj';
}}

// '#35', '#x23' or a name -> the characters it stands for, or null when it is
// not a reference HTML defines. A numeric reference to 0, a surrogate or past
// U+10FFFF is U+FFFD, as in CommonMark.
function decode(body) {{
  if (body[0] === '#') {{
    const hex = body[1] === 'x' || body[1] === 'X';
    const digits = body.slice(hex ? 2 : 1);
    if (!(hex ? /^[0-9a-fA-F]{{1,6}}$/ : /^[0-9]{{1,7}}$/).test(digits)) return null;
    const c = parseInt(digits, hex ? 16 : 10);
    return c === 0 || c > 0x10ffff || (c >= 0xd800 && c <= 0xdfff) ? '\\ufffd' : String.fromCodePoint(c);
  }}
  if (!map) build();
  const v = map[body];
  if (v !== undefined) return v;
  const m = /^([A-Za-z])(fr|opf|scr)$/.exec(body);
  if (!m) return null;
  const c = m[1].charCodeAt(0);
  return String.fromCodePoint(BASES[m[2]] + (c < 97 ? c - 65 : c - 71));
}}

module.exports = {{ decode }};
"""
    with open(OUT, 'w', encoding='utf-8') as f:
        f.write(src)
    print(f'wrote {os.path.relpath(OUT)}: {len(NAMES)} names, {len(src.encode("utf-8"))} bytes')


main()
